FORMAT: 1A
HOST: http://api.spiderlog.net/

# Spider Log
Provides API for the Server Log App family for recording spider sightings by users 

# Group Spiders
Access to Spider resources

## My Spiders [/spiders{?page,size}]
### Get all my spider sightings [GET]
+ Parameters
    + page ([required, number, 1])...  page, number
    + size ([required, number, 10])... size, number
+ Request

    + Header
    
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
        
+ Response 200 (application/json)
    
       + Header
       
            ETag: 'a45bef567def'
            cache-control: max-age=600
    
       + Body
    
            {
                "page":
                {
                    "number": 1,
                    "size":10,
                    "totalPages": 20
                },
                "spiders":
                [
                    {
                        "sightedAt": "2018-04-10T07:09",
                        "mageUrl":"uid-19447681/201804/14562881209_046ee56ef_z.jpg",
                        "description": "Spider I saw on the train",
                        "tags": [
                            "strpy"
                        ]
                    },
                    {
                        "sightedAt": "2018-03-10T07:09",
                        "imageUrl":"uid-19347681/201803/14562881209_046ee56ef_z.jpg",
                        "description": "Spider I saw on the Bus",
                        "tags": [
                            "big"
                        ]
                    },
                    {
                        "sightedAt": "2018-02-10T07:09",
                        "imageUrl":"uid-19047681/201802/14562881209_046ee56ef_z.jpg",
                        "description": "Spider I saw on the Car",
                        "tags": [
                            "hairy"
                        ]
                    },
                    {
                        "sightedAt": "2018-01-10T07:09",
                        "imageUrl":"uid-19147681/201801/14562881209_046ee56ef_z.jpg",
                        "description": "Spider I saw on the tree",
                        "tags": [
                            "silky"
                        ]
                    }
                ]
            }